server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "yoursupersecretpassword"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubeSearchEnabled: true
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0"
      repository: "https://maven.lavalink.dev/releases"
      
